

#ifndef USE_MAKE
//#define F031_DEV
// #define FD6288_F051
// #define IFLIGHT
// #define MP6531
// #define TMOTOR55     // like iflight but with leds
// #define TMOTOR45
// #define HGLRC
// #define SISKIN
// #define MAMBA_F50PRO
// #define WRAITH32
// #define AIKON20X20
// #define AIKONSINGLE
// #define FLYCOLOR
// #define HKMICRO
// #define AM32REF_F051
// #define BLPWR
// #define HVFLYCOLOR
// #define AM32REF_F051

// #define G072ESC
// #define G071ENABLE
// #define G071_OPEN_DRAIN
// #define G071_OPEN_DRAIN_B
// #define GEN_64K_G071
// define  DT120_G071

// #define WRAITH32_F421
// #define GD32DEV
// #define GD32DEV_B
// #define GD32SKYSTARS20
// #define GD32SKYSTARS25
// #define GD32SKYSTARS30
// #define GD32SKYSTARS40
#endif

// used to hold a port/pin in a single 16 bit integer
// used to hold a port/pin in a single 16 bit integer
#define GPIO_PORT_PIN(portnum, pinnum) ((portnum)<<8|(pinnum))

/*********************************************************************
 * AT32F421 targets using HARDWARE_GROUP_AT_B + HARDWARE_GROUP_AT_045
 *********************************************************************/

#ifdef LUMENIER_12S_F421
#define FIRMWARE_NAME "Lumenier 12s"
#define FILE_NAME "LUMENIER_12S_F421"
#define DEAD_TIME 120
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define CURRENT_ADC_PIN GPIO_PINS_3
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define USE_SERIAL_TELEMETRY
#define MILLIVOLT_PER_AMP 19
#define RAMP_SPEED_LOW_RPM 1
#define RAMP_SPEED_HIGH_RPM 1
#endif

#ifdef SEQURE_4IN1_F421
#define FIRMWARE_NAME "Sequre f4 "
#define FILE_NAME "SEQURE_4IN1_F421"
#define DEAD_TIME 80
#define CURRENT_ADC_PIN GPIO_PINS_2
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_2
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define MILLIVOLT_PER_AMP 9
#define USE_NTC
#define NTC_ADC_CHANNEL ADC_CHANNEL_3
#define NTC_ADC_PIN GPIO_PINS_3
#endif

#ifdef TBS_6S_4IN1_F421
#define FIRMWARE_NAME "TBSlu6s4in1"
#define FILE_NAME "TBS_6S_4IN1_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif

#ifdef  TBS_6S_F421
#define FIRMWARE_NAME "TBS 6S      "
#define FILE_NAME "TBS_6S_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif

#ifdef TBS_8S_4IN1_F421
#define FIRMWARE_NAME "TBSlu8s4in1"
#define FILE_NAME "TBS_8S_4IN1_F421"
#define DEAD_TIME 30
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif

#ifdef  FLYWOO_F421
#define FIRMWARE_NAME "FLYWOO_F421 "
#define FILE_NAME "FLYWOO_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif

#ifdef AT32DEV_F421
#define FIRMWARE_NAME "AT32PB4     "
#define FILE_NAME "AT32DEV_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif

#ifdef ZTW_A_F421
#define FIRMWARE_NAME "ZTW_A_F421 "
#define FILE_NAME "ZTW_A_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif

#ifdef ZTW_A_HV_F421
#define FIRMWARE_NAME "ZTW_HV_F421 "
#define FILE_NAME "ZTW_A_HV_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#define TARGET_VOLTAGE_DIVIDER 230
#define MILLIVOLT_PER_AMP 6
#define USE_NTC
#define NTC_ADC_CHANNEL ADC_CHANNEL_2
#define NTC_ADC_PIN GPIO_PINS_2
#endif

#ifdef GOOSKY_3S_F421
#define FIRMWARE_NAME "GOOSKY_F421 "
#define FILE_NAME "GOOSKY_3S_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_2
#define CURRENT_ADC_PIN GPIO_PINS_2
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_3
#define VOLTAGE_ADC_PIN GPIO_PINS_3
#define USE_NTC 
#define NTC_ADC_CHANNEL ADC_CHANNEL_6
#define NTC_ADC_PIN GPIO_PINS_6
#endif

#ifdef  SILENTFORCE_50_F421
#define FIRMWARE_NAME "Silent-50   "
#define FILE_NAME "SILENTFORCE_50_F421"
#define DEAD_TIME 25
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define MILLIVOLT_PER_AMP 20
#endif

#ifdef  HDZERO_HALO_F421
#define FIRMWARE_NAME "HDZ_HALO F4 "
#define FILE_NAME "HDZERO_HALO_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif

#ifdef JHEMCU_F421
#define FIRMWARE_NAME "JHEMCU_F421 "
#define FILE_NAME "JHEMCU_F421"
#define DEAD_TIME 80
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#define TARGET_MIN_BEMF_COUNTS 3
#endif

#ifdef FLASHHOBBY_F421
#define FIRMWARE_NAME "FH F421     "
#define FILE_NAME "FLASHHOBBY_F421"
#define DEAD_TIME 40
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifdef DAKEFPV_F421
#define FIRMWARE_NAME "DakeFpv F4  "
#define FILE_NAME "DAKEFPV_F421"
#define DEAD_TIME 50
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif

#ifdef NEUTRON_2_6S_AIO_F421
#define FIRMWARE_NAME "Neutron AIO"
#define FILE_NAME "NEUTRON_2_6S_AIO"
#define DEAD_TIME 40
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifdef AT32SLOTCAR_F421
#define FIRMWARE_NAME "AT32_SC     "
#define FILE_NAME "AT32SLOTCAR_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
//#define FIXED_DUTY_MODE
//#define FIXED_DUTY_MODE_POWER 100
#define DEBUG
#endif

#ifdef LUX_F7_HD_AIO_F421
#define FIRMWARE_NAME "LUX HD AIO"
#define FILE_NAME "LUX_F7_HD_AIO_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif

#ifdef RAZOR_LED_4IN1_F421
#define FIRMWARE_NAME "RAZOR LED"
#define FILE_NAME "RAZOR_LED_4IN1_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif

#ifdef RAZOR_PRO_F421
#define FIRMWARE_NAME "RAZOR PRO"
#define FILE_NAME "RAZOR_PRO_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif

#ifdef VORTEX_80A_F421
#define FIRMWARE_NAME "VORTEX_80A  "
#define FILE_NAME "VORTEX_80A_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define VOLTAGE_ADC_PIN GPIO_PINS_2
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_2
#define CURRENT_ADC_PIN GPIO_PINS_6
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_6
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 1
#define TARGET_VOLTAGE_DIVIDER 111
#endif

#ifdef VORTEX_100A_F421
#define FIRMWARE_NAME "VORTEX_100A "
#define FILE_NAME "VORTEX_100A_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_PIN GPIO_PINS_3
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define MILLIVOLT_PER_AMP 4
#define CURRENT_OFFSET 295
#define TARGET_VOLTAGE_DIVIDER 111
#endif

#ifdef XILO_STAX_V2_4IN1_F421
#define FIRMWARE_NAME "XILO STAX V2"
#define FILE_NAME "XILO_STAX_V2_4IN1_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif

#ifdef CBTECHNOLOGY_KIWI80A_F421
#define FIRMWARE_NAME "KIWI80_F421"
#define FILE_NAME "CBTECHNOLOGY_KIWI80A_F421"
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define VOLTAGE_ADC_PIN GPIO_PINS_3
#define DEAD_TIME 60
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_6
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_6
#define TARGET_VOLTAGE_DIVIDER 210
#define MILLIVOLT_PER_AMP 25
#define CURRENT_OFFSET 0
#define USE_SERIAL_TELEMETRY
#define USE_RGB_LED
#define RED_PORT    GPIOB
#define RED_PIN     GPIO_PINS_7
#define GREEN_PORT  GPIOB
#define GREEN_PIN   GPIO_PINS_5
#define BLUE_PORT   GPIOB
#define BLUE_PIN    GPIO_PINS_3
#endif

#ifdef CBTECHNOLOGY_SNIPE40A_F421
#define FIRMWARE_NAME "SNIPE40_F421"
#define FILE_NAME "CBTECHNOLOGY_SNIPE40A_F421"
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define VOLTAGE_ADC_PIN GPIO_PINS_3
#define DEAD_TIME 60
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_6
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_6 
#define TARGET_VOLTAGE_DIVIDER 210
#define MILLIVOLT_PER_AMP 50
#define CURRENT_OFFSET 0
#define USE_SERIAL_TELEMETRY
#endif

#ifdef GIPSY_F421
#define FIRMWARE_NAME "GiPSy F421  "
#define FILE_NAME "GIPSY_F421"
#define DEAD_TIME 80
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define TARGET_VOLTAGE_DIVIDER 110
#define MILLIVOLT_PER_AMP 50
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif

#ifdef  TEKKO32_4IN1_F421
#define FIRMWARE_NAME "Tekko32 4in1"
#define FILE_NAME "TEKKO32_4IN1_F421"
#define DEAD_TIME 80
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifdef  TBS_MINI_F421
#define FIRMWARE_NAME           "TBS Mini"
#define FILE_NAME                "TBS_MINI_F421"
#define DEAD_TIME               120
#define HARDWARE_GROUP_AT_045
#define HARDWARE_GROUP_AT_B
#define USE_INVERTED_HIGH
#define TARGET_MIN_BEMF_COUNTS 1
#define USE_STARTUP_BOOST
#define THREE_CELL_MAX
#endif

#ifdef AIKON_SINGLE_F421
#define FIRMWARE_NAME "AIKON S F4  "
#define FILE_NAME "AIKON_SINGLE_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifdef  AIKON_AT_04_F421
#define FIRMWARE_NAME "AIKON F421  "
#define FILE_NAME "AIKON_AT_04_F421"
#define DEAD_TIME 80
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define MILLIVOLT_PER_AMP 34
#define CURRENT_OFFSET 400 // millivolts
#endif

#ifdef JUPITER_50A_F421
#define FIRMWARE_NAME "Jupiter 50A "
#define FILE_NAME "JUPITER_50A_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifdef JUPITER_25A_F421
#define FIRMWARE_NAME "Jupiter 25A "
#define FILE_NAME "JUPITER_25A_F421"
#define DEAD_TIME 25
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifdef JUPITER_35A_F421
#define FIRMWARE_NAME "Jupiter 35A "
#define FILE_NAME "JUPITER_35A_F421"
#define DEAD_TIME 40
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifdef SKYSTARS_F60_F421
#define FIRMWARE_NAME "SKYSTARS_F60"
#define FILE_NAME "SKYSTARS_F60_F421"
#define DEAD_TIME 35
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_6
#define CURRENT_ADC_PIN GPIO_PINS_6
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_3
#define VOLTAGE_ADC_PIN GPIO_PINS_3
#define USE_NTC 
#define NTC_ADC_CHANNEL ADC_CHANNEL_2
#define NTC_ADC_PIN GPIO_PINS_2
#endif

#ifdef SKYSTARS_F80_F421
#define FIRMWARE_NAME "SKYSTARS_F80"
#define FILE_NAME "SKYSTARS_F80_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_6
#define CURRENT_ADC_PIN GPIO_PINS_6
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_3
#define VOLTAGE_ADC_PIN GPIO_PINS_3
#define USE_NTC 
#define NTC_ADC_CHANNEL ADC_CHANNEL_2
#define NTC_ADC_PIN GPIO_PINS_2
#endif

#ifdef PIONEER_35A_F421
#define FIRMWARE_NAME "Pioneer 35A "
#define FILE_NAME "PIONEER_35A_F421"
#define DEAD_TIME 40
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifdef PIONEER_25A_F421
#define FIRMWARE_NAME "Pioneer 25A "
#define FILE_NAME "PIONEER_25A_F421"
#define DEAD_TIME 40
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifdef SKYSTARS_AM60_V2_F421
#define FIRMWARE_NAME "F421 Am60   "
#define FILE_NAME "SKYSTARS_AM60_V2_F421"
#define DEAD_TIME 35
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifdef SKYSTARS_KO60_F421
#define FIRMWARE_NAME "F421 KO60   "
#define FILE_NAME "SKYSTARS_KO60_F421"
#define DEAD_TIME 50
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifdef SKYSTARS_KM65_F421
#define FIRMWARE_NAME "F421 KM65"
#define FILE_NAME "SKYSTARS_KM65_F421"
#define DEAD_TIME 70
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifdef SKYSTARS_KM55_V2_F421
#define FIRMWARE_NAME "KM55 F4     "
#define FILE_NAME "SKYSTARS_KM55_V2_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifdef SKYSTARS_AM60_THRUSTER_F421
#define FIRMWARE_NAME "F421 ROV   "
#define FILE_NAME "SKYSTARS_AM60_THRUSTER_F421"
#define DEAD_TIME 70
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define RAMP_SPEED_LOW_RPM 1
#define RAMP_SPEED_HIGH_RPM 1
#define TARGET_MIN_BEMF_COUNTS 6
#endif

#ifdef SKYSTARS_MVP60_F421
#define FIRMWARE_NAME "Skystars 60A"
#define FILE_NAME "SKYSTARS_MVP60_F421"
#define DEAD_TIME 70
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifdef  GSPACE_F421
#define FIRMWARE_NAME "GSPACE F421 "
#define FILE_NAME "GSPACE_F421"
#define DEAD_TIME 25
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_2
#define VOLTAGE_ADC_PIN GPIO_PINS_2
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define MILLIVOLT_PER_AMP 16
#endif

#ifdef  ODDITYRC_F421
#define FIRMWARE_NAME "ODDITYRC_F4"
#define FILE_NAME "ODDITYRC_F421"
#define DEAD_TIME 35
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define MILLIVOLT_PER_AMP 10
#endif

#ifdef  ODDITYRC_F80_F421
#define FIRMWARE_NAME "ODDITYRC_F80"
#define FILE_NAME "ODDITYRC_F80_F421"
#define DEAD_TIME 65
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_3
#define VOLTAGE_ADC_PIN GPIO_PINS_3
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_6
#define CURRENT_ADC_PIN GPIO_PINS_6
#define MILLIVOLT_PER_AMP 25
#define USE_RGB_LED
#define RED_PORT    GPIOB
#define RED_PIN     GPIO_PINS_8
#define GREEN_PORT  GPIOB
#define GREEN_PIN   GPIO_PINS_5
#define BLUE_PORT   GPIOB
#define BLUE_PIN    GPIO_PINS_3
#endif

#ifdef  JMITEST_1_2S_F421
#define FIRMWARE_NAME "JMI_1_2s_F4 "
#define FILE_NAME "JMITEST_1_2S_F421"
#define DEAD_TIME 120
#define HARDWARE_GROUP_AT_045
#define HARDWARE_GROUP_AT_B
#define USE_INVERTED_HIGH
#define USE_STARTUP_BOOST
#endif

#ifdef FREELYRC_F421
#define FIRMWARE_NAME "FreelyRC "
#define FILE_NAME "FREELYRC_F421"
#define DEAD_TIME 60
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define USE_LED_STRIP
#define WS2812_PIN GPIO_PINS_8
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_6
#define CURRENT_ADC_PIN GPIO_PINS_6
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_3
#define VOLTAGE_ADC_PIN GPIO_PINS_3
#endif

#ifndef FIRMWARE_NAME
/* if you get this then you have forgotten to add the section for your target above */
#error "Missing defines for target"
#endif

/********************************** defaults if not set
 * ***************************/

#ifndef TARGET_VOLTAGE_DIVIDER
#define TARGET_VOLTAGE_DIVIDER 110
#endif

#ifndef SINE_DIVIDER
#define SINE_DIVIDER 2
#endif

#ifndef MILLIVOLT_PER_AMP
#define MILLIVOLT_PER_AMP 20
#endif

#ifndef CURRENT_OFFSET
#define CURRENT_OFFSET 0
#endif

#ifndef TARGET_STALL_PROTECTION_INTERVAL
#define TARGET_STALL_PROTECTION_INTERVAL 6500
#endif

#ifndef RAMP_SPEED_STARTUP
#define RAMP_SPEED_STARTUP 2 // adjusted 2.14 to match duty cycle change between mcu targets.
#endif

#ifndef RAMP_SPEED_LOW_RPM // below commutation interval of 250us
#define RAMP_SPEED_LOW_RPM 6
#endif

#ifndef RAMP_SPEED_HIGH_RPM
#define RAMP_SPEED_HIGH_RPM 16
#endif

/************************************ AT32F421 Hardware Groups
 * ****************************/

#ifdef HARDWARE_GROUP_AT_B

#define MCU_AT421
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN GPIO_PINS_4
#define INPUT_PIN_SOURCE GPIO_PINS_SOURCE4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR3
#define INPUT_DMA_CHANNEL DMA1_CHANNEL4
#define IC_DMA_IRQ_NAME DMA1_Channel5_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PINS_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PINS_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_0
#define PHASE_B_PIN_SOURCE_LOW GPIO_PINS_SOURCE0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PINS_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_7
#define PHASE_C_PIN_SOURCE_LOW GPIO_PINS_SOURCE7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PINS_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_045
#define PHASE_A_COMP 0x400000E5 // pa0 Medium Comp Power
#define PHASE_B_COMP 0x400000C5 // pa4
#define PHASE_C_COMP 0x400000D5 // pa5
#endif

/************************************ MCU COMMON PERIPHERALS
 * **********************************************/

#ifdef MCU_AT421
#define ARTERY
#define CPU_FREQUENCY_MHZ 120
#define EEPROM_START_ADD (uint32_t)0x08007C00
#define INTERVAL_TIMER TMR6
#define TEN_KHZ_TIMER TMR14
#define UTILITY_TIMER TMR17
#define COM_TIMER TMR16
#define APPLICATION_ADDRESS 0x08001000
#define EXTI_LINE EXINT_LINE_21
#ifndef TARGET_MIN_BEMF_COUNTS
#define TARGET_MIN_BEMF_COUNTS 3
#endif
#define COMPARATOR_IRQ ADC1_CMP_IRQn
#define USE_ADC
#ifndef CURRENT_ADC_CHANNEL
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_6
#endif
#ifndef CURRENT_ADC_PIN
#define CURRENT_ADC_PIN GPIO_PINS_6
#endif
#ifndef VOLTAGE_ADC_CHANNEL
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_3
#endif
#ifndef VOLTAGE_ADC_PIN
#define VOLTAGE_ADC_PIN GPIO_PINS_3
#endif
#ifndef TEMP_ADC_CHANNEL
#define TEMP_ADC_CHANNEL ADC_CHANNEL_16
#endif
#define DSHOT_PRIORITY_THRESHOLD 50
#define COM_TIMER_IRQ TMR16_GLOBAL_IRQn
#endif

#ifndef LOOP_FREQUENCY_HZ
#define LOOP_FREQUENCY_HZ 20000
#endif

#define PID_LOOP_DIVIDER (LOOP_FREQUENCY_HZ / 1000)

// default to no DroneCAN support
#ifndef DRONECAN_SUPPORT
#define DRONECAN_SUPPORT 0
#elif DRONECAN_SUPPORT == 1
// all DroneCAN ESCs use 128k flash layout
#undef EEPROM_START_ADD
#define EEPROM_START_ADD (uint32_t)0x0801F800
#endif

#ifndef NOMINAL_PWM
// use a nominal PWM for commutation via TIM1 of 24kHz
#define NOMINAL_PWM 24000U
#endif

#ifndef TIM1_AUTORELOAD
// calculate commutation timer ARR based on a nominal 24kHz PWM
#define TIM1_AUTORELOAD    ((uint16_t)(CPU_FREQUENCY_MHZ * 1000U * 1000U / NOMINAL_PWM)-1)
#endif

#ifndef POLLING_MODE_THRESHOLD
#define POLLING_MODE_THRESHOLD 2000
#endif


