

#ifndef USE_MAKE
//#define F031_DEV
// #define FD6288_F051
// #define IFLIGHT
// #define MP6531
// #define TMOTOR55     // like iflight but with leds
// #define TMOTOR45
// #define HGLRC
// #define SISKIN
// #define MAMBA_F50PRO
// #define WRAITH32
// #define AIKON20X20
// #define AIKONSINGLE
// #define FLYCOLOR
// #define HKMICRO
// #define AM32REF_F051
// #define BLPWR
// #define HVFLYCOLOR
// #define AM32REF_F051

// #define G072ESC
// #define G071ENABLE
// #define G071_OPEN_DRAIN
// #define G071_OPEN_DRAIN_B
// #define GEN_64K_G071
// define  DT120_G071

// #define WRAITH32_F421
// #define GD32DEV
// #define GD32DEV_B
// #define GD32SKYSTARS20
// #define GD32SKYSTARS25
// #define GD32SKYSTARS30
// #define GD32SKYSTARS40
#endif

// used to hold a port/pin in a single 16 bit integer
#define GPIO_PORT_PIN(portnum, pinnum) ((portnum)<<8|(pinnum))

// GLOBAL
// #define USE_ADC_INPUT
// #define USE_ALKAS_DEBUG_LED


#ifdef  TEKKO32_4IN1_F421
#define FIRMWARE_NAME "Tekko32 4in1"
#define FILE_NAME "TEKKO32_4IN1_F421"
#define DEAD_TIME 80
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#endif

#ifndef FIRMWARE_NAME
/* if you get this then you have forgotten to add the section for your target above */
#error "Missing defines for target"
#endif

/********************************** defaults if not set
 * ***************************/

#ifndef TARGET_VOLTAGE_DIVIDER
#define TARGET_VOLTAGE_DIVIDER 110
#endif

#ifndef SINE_DIVIDER
#define SINE_DIVIDER 2
#endif

#ifndef MILLIVOLT_PER_AMP
#define MILLIVOLT_PER_AMP 20
#endif

#ifndef CURRENT_OFFSET
#define CURRENT_OFFSET 0
#endif

#ifndef TARGET_STALL_PROTECTION_INTERVAL
#define TARGET_STALL_PROTECTION_INTERVAL 6500
#endif

#ifndef RAMP_SPEED_STARTUP
#define RAMP_SPEED_STARTUP 2 // adjusted 2.14 to match duty cycle change between mcu targets.
#endif

#ifndef RAMP_SPEED_LOW_RPM // below commutation interval of 250us
#define RAMP_SPEED_LOW_RPM 6
#endif

#ifndef RAMP_SPEED_HIGH_RPM
#define RAMP_SPEED_HIGH_RPM 16
#endif

/************************************ F051 Hardware Groups
 * ****************************/

#ifdef HARDWARE_GROUP_F0_A

#define MCU_F051
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15
#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_5
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel4_5_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP COMP_PA5
#define PHASE_B_COMP COMP_PA4
#define PHASE_C_COMP COMP_PA0

#endif

#ifdef HARDWARE_GROUP_F0_B

#define MCU_F051
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3
#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_4
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel4_5_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP COMP_PA0
#define PHASE_B_COMP COMP_PA4
#define PHASE_C_COMP COMP_PA5

#endif

#ifdef HARDWARE_GROUP_F0_C

#define MCU_F051
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15
#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_5
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel4_5_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_B_GPIO_PORT_LOW GPIOA
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP COMP_PA4
#define PHASE_B_COMP COMP_PA5
#define PHASE_C_COMP COMP_PA0

#endif

#ifdef HARDWARE_GROUP_F0_E

#define MCU_F051
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15
#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_5
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel4_5_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_A_GPIO_PORT_LOW GPIOA
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP COMP_PA0
#define PHASE_B_COMP COMP_PA4
#define PHASE_C_COMP COMP_PA5

#endif

#ifdef HARDWARE_GROUP_F0_F

#define MCU_F051
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3
#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_4
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel4_5_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP COMP_PA5
#define PHASE_B_COMP COMP_PA0
#define PHASE_C_COMP COMP_PA4

#endif

#ifdef HARDWARE_GROUP_F0_G

#define MCU_F051
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3
#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_4
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel4_5_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP COMP_PA4
#define PHASE_B_COMP COMP_PA0
#define PHASE_C_COMP COMP_PA5

#define USE_INVERTED_LOW
// #define USE_INVERTED_HIGH
#define USE_OPEN_DRAIN_LOW
#define USE_OPEN_DRAIN_HIGH

#endif

#ifdef HARDWARE_GROUP_F0_H

#define MCU_F051
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3
#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_4
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel4_5_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define HARDWARE_GROUP_F0_540

#endif

#ifdef HARDWARE_GROUP_F0_U

#define MCU_F051
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3
#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_4
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel4_5_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_F0_045 
#define PHASE_A_COMP COMP_PA0 // pa0     
#define PHASE_B_COMP COMP_PA4 // pa4
#define PHASE_C_COMP COMP_PA5 // pa5
#endif
#ifdef HARDWARE_GROUP_F0_504 
#define PHASE_A_COMP COMP_PA5 // pa5            
#define PHASE_B_COMP COMP_PA0 // pa0
#define PHASE_C_COMP COMP_PA4 // pa4
#endif
#ifdef HARDWARE_GROUP_F0_450
#define PHASE_A_COMP COMP_PA4 // pa4           
#define PHASE_B_COMP COMP_PA5 // pa5
#define PHASE_C_COMP COMP_PA0 // pa0
#endif
#ifdef HARDWARE_GROUP_F0_054
#define PHASE_A_COMP COMP_PA0 // pa0            
#define PHASE_B_COMP COMP_PA5 // pa5
#define PHASE_C_COMP COMP_PA4 // pa4
#endif
#ifdef HARDWARE_GROUP_F0_405
#define PHASE_A_COMP COMP_PA4 // pa4            
#define PHASE_B_COMP COMP_PA0 // pa0
#define PHASE_C_COMP COMP_PA5 // pa5
#endif
#ifdef HARDWARE_GROUP_F0_540 
#define PHASE_A_COMP COMP_PA5 // pa5         
#define PHASE_B_COMP COMP_PA4 // pa4
#define PHASE_C_COMP COMP_PA0 // pa0
#endif

/************************************* G071 Hardware Groups
 * **********************************/

#ifdef HARDWARE_GROUP_G0_A

#define MCU_G071
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2

#endif

#ifdef HARDWARE_GROUP_G0_B

#define MCU_G071
#define PWM_ENABLE_BRIDGE
#define USE_TIMER_3_CHANNEL_1

#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_PWM LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_PWM GPIOA
#define PHASE_A_GPIO_ENABLE LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_ENABLE GPIOB

#define PHASE_B_GPIO_PWM LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_PWM GPIOA
#define PHASE_B_GPIO_ENABLE LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_ENABLE GPIOB

#define PHASE_C_GPIO_PWM LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_PWM GPIOA
#define PHASE_C_GPIO_ENABLE LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_ENABLE GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2

#endif

#ifdef HARDWARE_GROUP_G0_C

#define MCU_G071
#define OPEN_DRAIN_PWM
#define PWM_ENABLE_BRIDGE
#define USE_TIMER_3_CHANNEL_1

#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_PWM LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_PWM GPIOA
#define PHASE_A_GPIO_ENABLE LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_ENABLE GPIOB

#define PHASE_B_GPIO_PWM LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_PWM GPIOA
#define PHASE_B_GPIO_ENABLE LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_ENABLE GPIOB

#define PHASE_C_GPIO_PWM LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_PWM GPIOA
#define PHASE_C_GPIO_ENABLE LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_ENABLE GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2

#endif

#ifdef HARDWARE_GROUP_G0_D

#define MCU_G071
#define OPEN_DRAIN_PWM
#define PWM_ENABLE_BRIDGE
#define USE_TIMER_3_CHANNEL_1

#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_PWM LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_PWM GPIOA
#define PHASE_A_GPIO_ENABLE LL_GPIO_PIN_15
#define PHASE_A_GPIO_PORT_ENABLE GPIOA

#define PHASE_B_GPIO_PWM LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_PWM GPIOA
#define PHASE_B_GPIO_ENABLE LL_GPIO_PIN_6
#define PHASE_B_GPIO_PORT_ENABLE GPIOC

#define PHASE_C_GPIO_PWM LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_PWM GPIOA
#define PHASE_C_GPIO_ENABLE LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_ENABLE GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2
#endif

#ifdef HARDWARE_GROUP_G0_F

#define MCU_G071
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2

#endif

#ifdef HARDWARE_GROUP_G0_G

#define MCU_G071
#define N_VARIANT
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_6
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO3 // pa2
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa0

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_18
#define PHASE_A_COMP_NUMBER COMP2

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_18
#define PHASE_B_COMP_NUMBER COMP2

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_17
#define PHASE_C_COMP_NUMBER COMP1

#define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5

#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif

#ifdef HARDWARE_GROUP_G0_H

#define MCU_G071
#define N_VARIANT
#define USE_TIMER_16_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_6
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM16
#define IC_TIMER_POINTER htim16

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim16_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO3 // pa2
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa0

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_18
#define PHASE_A_COMP_NUMBER COMP2

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_18
#define PHASE_B_COMP_NUMBER COMP2

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_17
#define PHASE_C_COMP_NUMBER COMP1

#define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5

#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif
#ifdef HARDWARE_GROUP_G0_N

#define USE_LED_STRIP
#define MCU_G071
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2

#define VOLTAGE_ADC_PIN LL_GPIO_PIN_6
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_6

#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif

#ifdef HARDWARE_GROUP_G0_I

#define MCU_G071
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#ifndef PHASE_A_COMP
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#endif
#ifndef PHASE_B_COMP
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#endif
#ifndef PHASE_C_COMP
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2
#endif

#define VOLTAGE_ADC_PIN LL_GPIO_PIN_1
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_1

#define CURRENT_ADC_PIN LL_GPIO_PIN_5
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_5

#endif


#ifdef HARDWARE_GROUP_G0_J

#define MCU_G071
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_12
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_11
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2

#endif

#ifdef HARDWARE_GROUP_G0_K

#define MCU_G071
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO3 // pa2
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO2 // pb7

#endif

#ifdef HARDWARE_GROUP_G0_L

#define MCU_G071
#define N_VARIANT
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_6
#define INPUT_PIN_PORT GPIOC
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO3 // pa0
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO3 // pa2
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO2 // pb7

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_17
#define PHASE_A_COMP_NUMBER COMP1

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_18
#define PHASE_B_COMP_NUMBER COMP2

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_18
#define PHASE_C_COMP_NUMBER COMP2

#endif

#ifdef HARDWARE_GROUP_G4_A

#define MCU_G431
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_A_GPIO_PORT_LOW GPIOF
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA


#ifdef COMP_OVERRIDE

#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 //
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO1 //
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO2 //

#define PHASE_B_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO2  //pa3
#define PHASE_A_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO1  //pa1
#define PHASE_C_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO1  //pa1

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_22
#define PHASE_B_COMP_NUMBER COMP2

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_A_COMP_NUMBER COMP1

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_C_COMP_NUMBER COMP1

#else 


#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO1 //
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 //
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO2 //

#define PHASE_A_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO2  //pa3
#define PHASE_B_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO1  //pa1
#define PHASE_C_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO1  //pa1

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_22
#define PHASE_A_COMP_NUMBER COMP2

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_B_COMP_NUMBER COMP1

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_C_COMP_NUMBER COMP1

#endif

//#define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
//#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5

//#define CURRENT_ADC_PIN LL_GPIO_PIN_4
//#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif

#ifdef HARDWARE_GROUP_G4_B

#define MCU_G431
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO1 // pa4
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pa5
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO2 // pa0

#define PHASE_A_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO1  //pa1
#define PHASE_B_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO2  //pa3
#define PHASE_C_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO1  //pa1

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_A_COMP_NUMBER COMP1

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_22
#define PHASE_B_COMP_NUMBER COMP2

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_C_COMP_NUMBER COMP1

#define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5

#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif

#ifdef HARDWARE_GROUP_G4_C

#define MCU_G431
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_A_GPIO_PORT_LOW GPIOF
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pa0
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pa4
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO1 // pa5

#define PHASE_A_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO1  //pa1
#define PHASE_B_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO1  //pa1
#define PHASE_C_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO2  //pa3

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_A_COMP_NUMBER COMP1

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_B_COMP_NUMBER COMP1

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_22
#define PHASE_C_COMP_NUMBER COMP2


#endif

#ifdef HARDWARE_GROUP_G4_D

#define MCU_G431
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define AF_A_LOW LL_GPIO_AF_4
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_14
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_13
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO2 // pa0
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pa4
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO1 // pa5

#define PHASE_C_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO1  //pa1
#define PHASE_B_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO1  //pa1
#define PHASE_A_INPUT_PLUS  LL_COMP_INPUT_PLUS_IO2  //pa3

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_C_COMP_NUMBER COMP1

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_B_COMP_NUMBER COMP1

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_22
#define PHASE_A_COMP_NUMBER COMP2


#endif

/************************************ G031 Hardware Groups
 * ************************************************/

#ifdef HARDWARE_GROUP_F031_A

#define EXTI_TYPE_BAC
#define USE_TIMER_2_CHANNEL_3
#define MCU_F031

#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH3
#define IC_TIMER_REGISTER TIM2
#define IC_TIMER_POINTER htim2

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim2_ch3
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_EXTI_PORT GPIOF
#define PHASE_B_EXTI_PORT GPIOF
#define PHASE_C_EXTI_PORT GPIOA

#define PHASE_A_EXTI_PIN LL_GPIO_PIN_0
#define PHASE_B_EXTI_PIN LL_GPIO_PIN_1
#define PHASE_C_EXTI_PIN LL_GPIO_PIN_6

#define PHASE_A_EXTI_LINE 0
#define PHASE_B_EXTI_LINE 1
#define PHASE_C_EXTI_LINE 6

#define SYSCFG_EXTI_PORTA LL_SYSCFG_EXTI_PORTF
#define SYSCFG_EXTI_PORTB LL_SYSCFG_EXTI_PORTF
#define SYSCFG_EXTI_PORTC LL_SYSCFG_EXTI_PORTA

#define SYSCFG_EXTI_LINEA LL_SYSCFG_EXTI_LINE0
#define SYSCFG_EXTI_LINEB LL_SYSCFG_EXTI_LINE1
#define SYSCFG_EXTI_LINEC LL_SYSCFG_EXTI_LINE6

#define PHASE_A_LL_EXTI_LINE LL_EXTI_LINE_0
#define PHASE_B_LL_EXTI_LINE LL_EXTI_LINE_1
#define PHASE_C_LL_EXTI_LINE LL_EXTI_LINE_6

#define EXTI_IRQ1_NAME EXTI0_1_IRQn
#define EXTI_IRQ2_NAME EXTI4_15_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_14
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_13
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define CURRENT_SENSE_ADC_PIN LL_GPIO_PIN_5
#define VOLTAGE_SENSE_ADC_PIN LL_GPIO_PIN_7

#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_5
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_7

#endif

#ifdef HARDWARE_GROUP_F031_B

#define MCU_F031
#define USE_TIMER_2_CHANNEL_3
#define INPUT_PIN LL_GPIO_PIN_2
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH3
#define IC_TIMER_REGISTER TIM2
#define IC_TIMER_POINTER htim2

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim2_ch3
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_EXTI_PORT GPIOF
#define PHASE_B_EXTI_PORT GPIOF
#define PHASE_C_EXTI_PORT GPIOA

#define PHASE_A_EXTI_PIN LL_GPIO_PIN_0
#define PHASE_B_EXTI_PIN LL_GPIO_PIN_1
#define PHASE_C_EXTI_PIN LL_GPIO_PIN_5

#define PHASE_A_EXTI_LINE 0
#define PHASE_B_EXTI_LINE 1
#define PHASE_C_EXTI_LINE 5

#define SYSCFG_EXTI_PORTA LL_SYSCFG_EXTI_PORTF
#define SYSCFG_EXTI_PORTB LL_SYSCFG_EXTI_PORTF
#define SYSCFG_EXTI_PORTC LL_SYSCFG_EXTI_PORTA

#define SYSCFG_EXTI_LINEA LL_SYSCFG_EXTI_LINE0
#define SYSCFG_EXTI_LINEB LL_SYSCFG_EXTI_LINE1
#define SYSCFG_EXTI_LINEC LL_SYSCFG_EXTI_LINE5

#define PHASE_A_LL_EXTI_LINE LL_EXTI_LINE_0
#define PHASE_B_LL_EXTI_LINE LL_EXTI_LINE_1
#define PHASE_C_LL_EXTI_LINE LL_EXTI_LINE_5

#define EXTI_IRQ1_NAME EXTI0_1_IRQn
#define EXTI_IRQ2_NAME EXTI4_15_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_14
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_13
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define CURRENT_SENSE_ADC_PIN LL_GPIO_PIN_3
#define VOLTAGE_SENSE_ADC_PIN LL_GPIO_PIN_4

#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_3
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif

#ifdef HARDWARE_GROUP_F031_C

#define MCU_F031
#define USE_TIMER_16
#define INPUT_PIN LL_GPIO_PIN_6
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM16
#define IC_TIMER_POINTER htim16

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_3
#define DMA_HANDLE_TYPE_DEF hdma_tim16_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel2_3_IRQn

#define PHASE_A_EXTI_PORT GPIOF
#define PHASE_B_EXTI_PORT GPIOB
#define PHASE_C_EXTI_PORT GPIOB

#define PHASE_A_EXTI_PIN LL_GPIO_PIN_0
#define PHASE_B_EXTI_PIN LL_GPIO_PIN_1
#define PHASE_C_EXTI_PIN LL_GPIO_PIN_7

#define PHASE_A_EXTI_LINE 0
#define PHASE_B_EXTI_LINE 1
#define PHASE_C_EXTI_LINE 7

#define SYSCFG_EXTI_PORTA LL_SYSCFG_EXTI_PORTF
#define SYSCFG_EXTI_PORTB LL_SYSCFG_EXTI_PORTB
#define SYSCFG_EXTI_PORTC LL_SYSCFG_EXTI_PORTB

#define SYSCFG_EXTI_LINEA LL_SYSCFG_EXTI_LINE0
#define SYSCFG_EXTI_LINEB LL_SYSCFG_EXTI_LINE1
#define SYSCFG_EXTI_LINEC LL_SYSCFG_EXTI_LINE7

#define PHASE_A_LL_EXTI_LINE LL_EXTI_LINE_0
#define PHASE_B_LL_EXTI_LINE LL_EXTI_LINE_1
#define PHASE_C_LL_EXTI_LINE LL_EXTI_LINE_7

#define EXTI_IRQ1_NAME EXTI0_1_IRQn
#define EXTI_IRQ2_NAME EXTI4_15_IRQn


#define PHASE_A_GPIO_LOW LL_GPIO_PIN_14
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_13
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

/***********************************************************************************************************/

#ifdef HARDWARE_GROUP_GD_A

#define MCU_GDE23
#define INPUT_PIN GPIO_PIN_4
#define INPUT_PIN_AF GPIO_AF_1
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL TIMER_CH_0
#define USE_TIMER_2_CHANNEL_0
#define IC_TIMER_REGISTER TIMER2
#define INPUT_DMA_CHANNEL DMA_CH3
#define LED_TIMER_REGISTER TIMER14
#define LED_DMA_CHANNEL DMA_CH4
#define LED_USES_PA2
#define IC_DMA_IRQ_NAME DMA_Channel3_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP 0x61 // CMP_PA0
#define PHASE_B_COMP 0x41 // CMP_PA4
#define PHASE_C_COMP 0x51 // CMP_PA5

#endif

#ifdef HARDWARE_GROUP_GD_B

#define MCU_GDE23
#define INPUT_PIN GPIO_PIN_4
#define INPUT_PIN_AF GPIO_AF_1
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL TIMER_CH_0
#define USE_TIMER_2_CHANNEL_0
#define IC_TIMER_REGISTER TIMER2
#define INPUT_DMA_CHANNEL DMA_CH3
#define LED_TIMER_REGISTER TIMER14
#define LED_DMA_CHANNEL DMA_CH4
#define LED_USES_PA2
#define IC_DMA_IRQ_NAME DMA_Channel3_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PIN_8
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PIN_7
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP 0x61 // CMP_PA0
#define PHASE_B_COMP 0x41 // CMP_PA4
#define PHASE_C_COMP 0x51 // CMP_PA5

#endif

#ifdef HARDWARE_GROUP_GD_C

#define MCU_GDE23
#define INPUT_PIN GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define INPUT_PIN_AF GPIO_AF_0
#define IC_TIMER_CHANNEL TIMER_CH_0
#define USE_TIMER_14_CHANNEL_0
#define IC_TIMER_REGISTER TIMER14
#define INPUT_DMA_CHANNEL DMA_CH4
#define LED_TIMER_REGISTER TIMER2
#define LED_DMA_CHANNEL DMA_CH3
#define LED_USES_PB4
#define IC_DMA_IRQ_NAME DMA_Channel3_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP 0x61 // CMP_PA0
#define PHASE_B_COMP 0x51 // CMP_PA5
#define PHASE_C_COMP 0x41 // CMP_PA4

#endif


#ifdef HARDWARE_GROUP_AT_B

#define MCU_AT421
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN GPIO_PINS_4
#define INPUT_PIN_SOURCE GPIO_PINS_SOURCE4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR3
#define INPUT_DMA_CHANNEL DMA1_CHANNEL4
#define IC_DMA_IRQ_NAME DMA1_Channel5_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PINS_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PINS_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_0
#define PHASE_B_PIN_SOURCE_LOW GPIO_PINS_SOURCE0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PINS_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_7
#define PHASE_C_PIN_SOURCE_LOW GPIO_PINS_SOURCE7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PINS_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_C

#define MCU_AT421
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN GPIO_PINS_2
#define INPUT_PIN_SOURCE GPIO_PINS_SOURCE2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR15
#define INPUT_DMA_CHANNEL DMA1_CHANNEL5
#define IC_DMA_IRQ_NAME DMA1_Channel5_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PINS_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PINS_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_0
#define PHASE_B_PIN_SOURCE_LOW GPIO_PINS_SOURCE0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PINS_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_7
#define PHASE_C_PIN_SOURCE_LOW GPIO_PINS_SOURCE7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PINS_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_D

#define MCU_AT415
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN GPIO_PINS_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR3
#define INPUT_DMA_CHANNEL DMA1_CHANNEL6
#define IC_DMA_IRQ_NAME DMA1_Channel6_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PIN_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PIN_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_0
#define PHASE_B_PIN_SOURCE_LOW GPIO_PIN_SOURCE0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PIN_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_7
#define PHASE_C_PIN_SOURCE_LOW GPIO_PIN_SOURCE7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PIN_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_H

#define MCU_AT415
#define USE_TIMER_2_CHANNEL_3
#define INPUT_PIN GPIO_PINS_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_3
#define IC_TIMER_REGISTER TMR2
#define INPUT_DMA_CHANNEL DMA1_CHANNEL6
#define IC_DMA_IRQ_NAME DMA1_Channel6_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PIN_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PIN_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_0
#define PHASE_B_PIN_SOURCE_LOW GPIO_PIN_SOURCE0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PIN_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_7
#define PHASE_C_PIN_SOURCE_LOW GPIO_PIN_SOURCE7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PIN_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_E

#define MCU_AT421
#define USE_TIMER_15_CHANNEL_1
// #define USE_PA14_TELEMETRY
#define USE_PA6_TEMP
#define INPUT_PIN GPIO_PINS_2
#define INPUT_PIN_SOURCE GPIO_PINS_SOURCE2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR15
#define INPUT_DMA_CHANNEL DMA1_CHANNEL5
#define IC_DMA_IRQ_NAME DMA1_Channel5_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PINS_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PINS_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_0
#define PHASE_B_PIN_SOURCE_LOW GPIO_PINS_SOURCE0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PINS_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_7
#define PHASE_C_PIN_SOURCE_LOW GPIO_PINS_SOURCE7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PINS_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_F

#define MCU_AT421
#define USE_TIMER_15_CHANNEL_1
// #define USE_PA14_TELEMETRY
// #define USE_PA6_TEMP
#define INPUT_PIN GPIO_PINS_2
#define INPUT_PIN_SOURCE GPIO_PINS_SOURCE2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR15
#define INPUT_DMA_CHANNEL DMA1_CHANNEL5
#define IC_DMA_IRQ_NAME DMA1_Channel5_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PINS_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PINS_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_7
#define PHASE_B_PIN_SOURCE_LOW GPIO_PINS_SOURCE7
#define PHASE_B_GPIO_PORT_LOW GPIOA
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PINS_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_0
#define PHASE_C_PIN_SOURCE_LOW GPIO_PINS_SOURCE0
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PINS_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_045
#define PHASE_A_COMP 0x400000E5 // pa0 Medium Comp Power
#define PHASE_B_COMP 0x400000C5 // pa4
#define PHASE_C_COMP 0x400000D5 // pa5
#endif
#ifdef HARDWARE_GROUP_AT_504
#define PHASE_A_COMP 0x400000D5 // pa5           
#define PHASE_B_COMP 0x400000E5 // pa0
#define PHASE_C_COMP 0x400000C5 // pa4
#endif
#ifdef HARDWARE_GROUP_AT_450
#define PHASE_A_COMP 0x400000C5 // pa4            
#define PHASE_B_COMP 0x400000D5 // pa5
#define PHASE_C_COMP 0x400000E5 // pa0
#endif
#ifdef HARDWARE_GROUP_AT_054
#define PHASE_A_COMP 0x400000E5 // pa0            
#define PHASE_B_COMP 0x400000D5 // pa5
#define PHASE_C_COMP 0x400000C5 // pa4
#endif
#ifdef HARDWARE_GROUP_AT_405
#define PHASE_A_COMP 0x400000C5 // pa4            
#define PHASE_B_COMP 0x400000E5 // pa0
#define PHASE_C_COMP 0x400000D5 // pa5
#endif
#ifdef HARDWARE_GROUP_AT_540
#define PHASE_A_COMP 0x400000D5 // pa5           
#define PHASE_B_COMP 0x400000C5 // pa4
#define PHASE_C_COMP 0x400000E5 // pa0
#endif

#ifdef HARDWARE_GROUP_AT_245
#define PHASE_A_COMP 0x400000F5 // pa2     // works for polling mode
#define PHASE_B_COMP 0x400000C5 // pa4
#define PHASE_C_COMP 0x400000D5 // pa5
#endif

#ifdef     HARDWARE_GROUP_L4_A

#define    MCU_L431
#define    USE_TIMER_15_CHANNEL_1
#define    INPUT_PIN               LL_GPIO_PIN_2
#define    INPUT_PIN_PORT              GPIOA
#define    IC_TIMER_CHANNEL         LL_TIM_CHANNEL_CH1
#define    IC_TIMER_REGISTER          TIM15
#define    IC_TIMER_POINTER           htim15

#define    INPUT_DMA_CHANNEL       LL_DMA_CHANNEL_5
#define    DMA_HANDLE_TYPE_DEF     hdma_tim15_ch1
#define    IC_DMA_IRQ_NAME         DMA1_Channel5_IRQn

#define PHASE_A_GPIO_LOW          LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW         GPIOB
#define PHASE_A_GPIO_HIGH          LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH         GPIOA

#define PHASE_B_GPIO_LOW          LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW         GPIOB
#define PHASE_B_GPIO_HIGH          LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH         GPIOA

#define PHASE_C_GPIO_LOW          LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW         GPIOA
#define PHASE_C_GPIO_HIGH          LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH         GPIOA

#define USE_COMP_1

#ifdef COMP_ORDER_L4_A_045
#define PHASE_A_COMP  LL_COMP_INPUT_MINUS_IO3  // pa0
#define PHASE_B_COMP  LL_COMP_INPUT_MINUS_IO4  // pa4
#define PHASE_C_COMP  LL_COMP_INPUT_MINUS_IO5  // pa5
#endif

#ifdef COMP_ORDER_L4_A_540
#define PHASE_A_COMP  LL_COMP_INPUT_MINUS_IO5  // pa5  /// THIS CONFIG FOR T-MOTOR
#define PHASE_B_COMP  LL_COMP_INPUT_MINUS_IO4  // pa4
#define PHASE_C_COMP  LL_COMP_INPUT_MINUS_IO3  // pa0
#endif

#define COMMON_COMP LL_COMP_INPUT_PLUS_IO3

#define CURRENT_SENSE_ADC_PIN        LL_GPIO_PIN_3
#define VOLTAGE_SENSE_ADC_PIN        LL_GPIO_PIN_6

#define CURRENT_ADC_CHANNEL         LL_ADC_CHANNEL_8
#define VOLTAGE_ADC_CHANNEL         LL_ADC_CHANNEL_11

#endif


#ifdef     HARDWARE_GROUP_L4_B

#define MCU_L431
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA

#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_5
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel5_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA


#define USE_COMP_2
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2  // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO5  // pa5
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO4  // pa4
#define COMMON_COMP  LL_COMP_INPUT_PLUS_IO1
//#define USE_LED_STRIP
//#define WS2812_PIN LL_GPIO_PIN_3

#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_8
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_11
#define ADC_CHANNEL_TEMP LL_ADC_CHANNEL_6

#endif

#ifdef     HARDWARE_GROUP_L4_C

#define    MCU_L431
#define    USE_TIMER_15_CHANNEL_1
#define    INPUT_PIN               LL_GPIO_PIN_2
#define    INPUT_PIN_PORT              GPIOA
#define    IC_TIMER_CHANNEL         LL_TIM_CHANNEL_CH1
#define    IC_TIMER_REGISTER          TIM15
#define    IC_TIMER_POINTER           htim15

#define    INPUT_DMA_CHANNEL       LL_DMA_CHANNEL_5
#define    DMA_HANDLE_TYPE_DEF     hdma_tim15_ch1
#define    IC_DMA_IRQ_NAME         DMA1_Channel5_IRQn

#define PHASE_A_GPIO_LOW          LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW         GPIOB
#define PHASE_A_GPIO_HIGH          LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH         GPIOA

#define PHASE_B_GPIO_LOW          LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW         GPIOB
#define PHASE_B_GPIO_HIGH          LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH         GPIOA

#define PHASE_C_GPIO_LOW          LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW         GPIOA
#define PHASE_C_GPIO_HIGH          LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH         GPIOA

#define USE_COMP_1

#define COMMON_COMP LL_COMP_INPUT_PLUS_IO3  //pa1

#define CURRENT_SENSE_ADC_PIN        LL_GPIO_PIN_3
#define VOLTAGE_SENSE_ADC_PIN        LL_GPIO_PIN_6

#define CURRENT_ADC_CHANNEL         LL_ADC_CHANNEL_8
#define VOLTAGE_ADC_CHANNEL         LL_ADC_CHANNEL_11

#endif

#ifdef HARDWARE_GROUP_L4_045
#define PHASE_A_COMP  LL_COMP_INPUT_MINUS_IO3  // pa0
#define PHASE_B_COMP  LL_COMP_INPUT_MINUS_IO4  // pa4
#define PHASE_C_COMP  LL_COMP_INPUT_MINUS_IO5  // pa5
#endif

#ifdef HARDWARE_GROUP_L4_054
#define PHASE_A_COMP  LL_COMP_INPUT_MINUS_IO3  // pa0
#define PHASE_B_COMP  LL_COMP_INPUT_MINUS_IO5  // pa5
#define PHASE_C_COMP  LL_COMP_INPUT_MINUS_IO4  // pa4
#endif

#ifdef     HARDWARE_GROUP_L4_N

#define    MCU_L431
#define    USE_TIMER_15_CHANNEL_1
#define    INPUT_PIN               LL_GPIO_PIN_2
#define    INPUT_PIN_PORT              GPIOA
#define    IC_TIMER_CHANNEL         LL_TIM_CHANNEL_CH1
#define    IC_TIMER_REGISTER          TIM15
#define    IC_TIMER_POINTER           htim15

#define    INPUT_DMA_CHANNEL       LL_DMA_CHANNEL_5
#define    DMA_HANDLE_TYPE_DEF     hdma_tim15_ch1
#define    IC_DMA_IRQ_NAME         DMA1_Channel5_IRQn

#define PHASE_A_GPIO_LOW          LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW         GPIOB
#define PHASE_A_GPIO_HIGH          LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH         GPIOA

#define PHASE_B_GPIO_LOW          LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW         GPIOB
#define PHASE_B_GPIO_HIGH          LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH         GPIOA

#define PHASE_C_GPIO_LOW          LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW         GPIOA
#define PHASE_C_GPIO_HIGH          LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH         GPIOA

#define USE_COMP_2
#define PHASE_A_COMP  LL_COMP_INPUT_MINUS_IO2  // pb7
#define PHASE_B_COMP  LL_COMP_INPUT_MINUS_IO5  // pa5
#define PHASE_C_COMP  LL_COMP_INPUT_MINUS_IO4  // pa4
#define COMMON_COMP   LL_COMP_INPUT_PLUS_IO1


#define CURRENT_SENSE_ADC_PIN        LL_GPIO_PIN_3
#define VOLTAGE_SENSE_ADC_PIN        LL_GPIO_PIN_6

#define CURRENT_ADC_CHANNEL         LL_ADC_CHANNEL_8
#define VOLTAGE_ADC_CHANNEL         LL_ADC_CHANNEL_11

#endif

//NXP hardware group of the MCXA153
#ifdef     HARDWARE_GROUP_NXP_MCXA153

#define    MCU_A153

//This is the Dshot/PWM input pin
#define    INPUT_PIN            	2		//P1.2
#define    INPUT_PIN_PORT        	PORT1
#define    INPUT_PIN_GPIO			GPIO1
#define    INPUT_PIN_CAPTURE_INP	1		//CT_INP0, check datasheet for correct value
#define    INPUT_PIN_ALT_FUNC		5		//CTIMER Capture input

//This is the Dshot/PWM timer
#define    IC_TIMER_REGISTER    	CTIMER0

//This is the DMA used for the Dshot/PWM data transfer
#define    INPUT_DMA_CHANNEL       	0 				//DMA channel 0
#define    IC_DMA_IRQ_NAME         	DMA_CH0_IRQn

//Assign the pins/PORTs/GPIOs for each gate signal
#define PHASE_A_PIN_LOW       		0		//Pin number
#define PHASE_A_PORT_LOW   			PORT3	//PORT number
#define PHASE_A_GPIO_LOW   			GPIO3	//GPIO number
#define PHASE_A_PIN_HIGH       		1
#define PHASE_A_PORT_HIGH    		PORT3
#define PHASE_A_GPIO_HIGH			GPIO3

#define PHASE_B_PIN_LOW         	8
#define PHASE_B_PORT_LOW     		PORT3
#define PHASE_B_GPIO_LOW			GPIO3
#define PHASE_B_PIN_HIGH      		9
#define PHASE_B_PORT_HIGH   		PORT3
#define PHASE_B_GPIO_HIGH			GPIO3

#define PHASE_C_PIN_LOW       		10
#define PHASE_C_PORT_LOW   			PORT3
#define PHASE_C_GPIO_LOW			GPIO3
#define PHASE_C_PIN_HIGH   			11
#define PHASE_C_PORT_HIGH			PORT3
#define PHASE_C_GPIO_HIGH			GPIO3

#define PHASE_A_COMP_INP  	3  		//P1.0 COMP0_IN3
#define PHASE_A_COMP_UNIT 	CMP0
#define PHASE_B_COMP_INP  	3  		//P1.1 COMP1_IN3
#define PHASE_B_COMP_UNIT 	CMP1
#define PHASE_C_COMP_INP  	1  		//P1.3 COMP0_IN1
#define PHASE_C_COMP_UNIT 	CMP0

#define COMMON_COMP0_INP	0		//P2.2 COMP0_IN0
#define COMMON_COMP1_INP	0		//P2.3 COMP1_IN0

//Assign UART pins and module
#define SERIAL_TELEMETRY				LPUART1
#define SERIAL_TELEMETRY_MODULE 		1
#define SERIAL_TELEMETRY_TX_PORT 		PORT1	//P1.9
#define SERIAL_TELEMETRY_TX_PIN 		9
#define SERIAL_TELEMETRY_TX_ALT_FUNC 	2

//Assign ADC pins and channels
#define CURRENT_SENSE_ADC_PIN     	7		//P2.7
#define VOLTAGE_SENSE_ADC_PIN      	16		//P2.16
#define SENSE_ADC_PORT 				PORT2

#define CURRENT_ADC_CHANNEL         7
#define VOLTAGE_ADC_CHANNEL         6
#define TEMP_ADC_CHANNEL 			26

//#define LOOP_FREQUENCY_HZ 10000
#endif
/************************************ G031 Hardware Groups
 * ************************************************/

#ifdef HARDWARE_GROUP_G031_A

#define MCU_G031
//#define EXTI_TYPE_BAC            // ??

#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_6
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_EXTI_PORT GPIOC
#define PHASE_B_EXTI_PORT GPIOB
#define PHASE_C_EXTI_PORT GPIOB

#define PHASE_A_EXTI_PIN LL_GPIO_PIN_14
#define PHASE_B_EXTI_PIN LL_GPIO_PIN_7
#define PHASE_C_EXTI_PIN LL_GPIO_PIN_1

#define PHASE_A_EXTI_LINE 14
#define PHASE_B_EXTI_LINE 7
#define PHASE_C_EXTI_LINE 1

#define SYSCFG_EXTI_PORTA LL_EXTI_CONFIG_PORTC
#define SYSCFG_EXTI_PORTB LL_EXTI_CONFIG_PORTB
#define SYSCFG_EXTI_PORTC LL_EXTI_CONFIG_PORTB

#define SYSCFG_EXTI_LINEA LL_EXTI_CONFIG_LINE14
#define SYSCFG_EXTI_LINEB LL_EXTI_CONFIG_LINE7
#define SYSCFG_EXTI_LINEC LL_EXTI_CONFIG_LINE1

#define PHASE_A_LL_EXTI_LINE LL_EXTI_LINE_14
#define PHASE_B_LL_EXTI_LINE LL_EXTI_LINE_7
#define PHASE_C_LL_EXTI_LINE LL_EXTI_LINE_1

#define EXTI_IRQ1_NAME EXTI0_1_IRQn
#define EXTI_IRQ2_NAME EXTI4_15_IRQn


//#define PHASE_A_GPIO_LOW LL_GPIO_PIN_15
//#define PHASE_A_GPIO_PORT_LOW GPIOB
//#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
//#define PHASE_A_GPIO_PORT_HIGH GPIOA

//#define PHASE_B_GPIO_LOW LL_GPIO_PIN_14
//#define PHASE_B_GPIO_PORT_LOW GPIOB
//#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
//#define PHASE_B_GPIO_PORT_HIGH GPIOA

//#define PHASE_C_GPIO_LOW LL_GPIO_PIN_13
//#define PHASE_C_GPIO_PORT_LOW GPIOB
//#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
//#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_14
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_13
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_C_GPIO_PORT_HIGH GPIOA



#define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5

#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif


#ifdef HARDWARE_GROUP_CH_A

#define MCU_CH32V203
#define USE_TIMER_15_CHANNEL_1

#define INPUT_PIN GPIO_Pin_0
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL        (1-1)
#define IC_TIMER_REGISTER       TIM2
#define INPUT_DMA_CHANNEL       DMA1_Channel5
#define IC_DMA_IRQ_NAME         DMA1_Channel5_IRQn

#define PHASE_A_GPIO_LOW        GPIO_Pin_1
#define PHASE_A_GPIO_PORT_LOW   GPIOB
#define PHASE_A_GPIO_HIGH       GPIO_Pin_10
#define PHASE_A_GPIO_PORT_HIGH  GPIOA

#define PHASE_B_GPIO_LOW        GPIO_Pin_0
#define PHASE_B_GPIO_PORT_LOW   GPIOB
#define PHASE_B_GPIO_HIGH       GPIO_Pin_9
#define PHASE_B_GPIO_PORT_HIGH  GPIOA

#define PHASE_C_GPIO_LOW        GPIO_Pin_7
#define PHASE_C_GPIO_PORT_LOW   GPIOA
#define PHASE_C_GPIO_HIGH       GPIO_Pin_8
#define PHASE_C_GPIO_PORT_HIGH  GPIOA


#endif

/************************************ MCU COMMON PERIPHERALS
 * **********************************************/

#ifdef MCU_F051
#define STMICRO
#define CPU_FREQUENCY_MHZ 48
#define EEPROM_START_ADD (uint32_t)0x08007C00
#define INTERVAL_TIMER TIM2
#define TEN_KHZ_TIMER TIM6
#define UTILITY_TIMER TIM17
#define COM_TIMER TIM14
#define APPLICATION_ADDRESS 0x08001000
#define MAIN_COMP COMP1
#define EXTI_LINE LL_EXTI_LINE_21
#ifndef TARGET_MIN_BEMF_COUNTS
#define TARGET_MIN_BEMF_COUNTS 2
#endif
#define COMPARATOR_IRQ ADC1_COMP_IRQn
#define USE_ADC
#ifndef CURRENT_ADC_PIN
#define CURRENT_ADC_PIN LL_GPIO_PIN_6
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_6
#endif
#ifndef VOLTAGE_ADC_PIN
#define VOLTAGE_ADC_PIN LL_GPIO_PIN_3
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_3
#endif
#define COM_TIMER_IRQ TIM14_IRQn
#define DSHOT_PRIORITY_THRESHOLD 120
#define COMP_PA0 0b1100001
#define COMP_PA4 0b1000001
#define COMP_PA5 0b1010001
#endif

#ifdef  MCU_F031
#define NEED_INPUT_READY
#define STMICRO
#define CPU_FREQUENCY_MHZ 48
#define EEPROM_START_ADD (uint32_t)0x08007C00
#define INTERVAL_TIMER TIM3
#ifdef USE_TIMER_16
#define TEN_KHZ_TIMER TIM2
#else
#define TEN_KHZ_TIMER TIM16
#endif
#define UTILITY_TIMER TIM17
#define COM_TIMER TIM14
#define APPLICATION_ADDRESS 0x08001000
#define TARGET_MIN_BEMF_COUNTS 2
// #define USE_SERIAL_TELEMETRY // moved to individual ESCs
#define USE_ADC
#define LOOP_FREQUENCY_HZ 20000
#define POLLING_MODE_THRESHOLD 500
#endif

#ifdef MCU_G071
#define STMICRO
#define CPU_FREQUENCY_MHZ 64
#ifdef SIXTY_FOUR_KB_MEMORY
#define EEPROM_START_ADD (uint32_t)0x0800F800
#else
#define EEPROM_START_ADD (uint32_t)0x0801F800
#endif
#define INTERVAL_TIMER TIM2
#define TEN_KHZ_TIMER TIM6
#define UTILITY_TIMER TIM17
#define COM_TIMER TIM14
#define APPLICATION_ADDRESS 0x08001000
#define MAIN_COMP COMP2
#define EXTI_LINE LL_EXTI_LINE_18

#ifndef TARGET_MIN_BEMF_COUNTS
#define TARGET_MIN_BEMF_COUNTS 2
#endif
#define COMPARATOR_IRQ ADC1_COMP_IRQn
#define USE_ADC
#ifndef CURRENT_ADC_CHANNEL
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_5
#endif
#ifndef VOLTAGE_ADC_CHANNEL
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_6
#endif
#ifndef CURRENT_ADC_PIN
#define CURRENT_ADC_PIN LL_GPIO_PIN_5
#endif
#ifndef VOLTAGE_ADC_PIN
#define VOLTAGE_ADC_PIN LL_GPIO_PIN_6
#endif
#define DSHOT_PRIORITY_THRESHOLD 60
#define COM_TIMER_IRQ TIM14_IRQn
#endif

#ifdef MCU_G031
#define STMICRO
#define CPU_FREQUENCY_MHZ 64
#define EEPROM_START_ADD (uint32_t)0x0800F800
#define INTERVAL_TIMER TIM2
#define TEN_KHZ_TIMER TIM16
#define UTILITY_TIMER TIM17
#define COM_TIMER TIM14
#define APPLICATION_ADDRESS 0x08001000

#ifndef TARGET_MIN_BEMF_COUNTS
#define TARGET_MIN_BEMF_COUNTS 2
#endif
//#define COMPARATOR_IRQ ADC1_COMP_IRQn
#define USE_ADC
#ifndef CURRENT_ADC_CHANNEL
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4
#endif
#ifndef VOLTAGE_ADC_CHANNEL
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5
#endif
#ifndef CURRENT_ADC_PIN
#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#endif
#ifndef VOLTAGE_ADC_PIN
#define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
#endif
#define DSHOT_PRIORITY_THRESHOLD 60
#define COM_TIMER_IRQ TIM14_IRQn
#endif


#ifdef MCU_G431
#define STMICRO
#define CPU_FREQUENCY_MHZ 160
#ifndef EEPROM_START_ADD
#define EEPROM_START_ADD (uint32_t)0x0800F800
#endif
#define INTERVAL_TIMER TIM2
#define TEN_KHZ_TIMER TIM6
#define UTILITY_TIMER TIM17
#define COM_TIMER TIM16
#define APPLICATION_ADDRESS 0x08001000
#define MAIN_COMP COMP2
#define EXTI_LINE LL_EXTI_LINE_22
#define TARGET_MIN_BEMF_COUNTS 3
#define COMPARATOR_IRQ COMP1_2_3_IRQn
#define USE_ADC
 #ifndef VOLTAGE_ADC_CHANNEL
 #define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_6
 #endif
 #ifndef VOLTAGE_ADC_PIN
 #define VOLTAGE_ADC_PIN LL_GPIO_PIN_6
 #endif
#ifndef AF_A_LOW
  #define AF_A_LOW LL_GPIO_AF_6
#endif
#ifndef AF_B_LOW
  #define AF_B_LOW LL_GPIO_AF_6
#endif
#ifndef AF_C_LOW
  #define AF_C_LOW LL_GPIO_AF_6
#endif
 
#define DSHOT_PRIORITY_THRESHOLD 60
#define COM_TIMER_IRQ TIM1_UP_TIM16_IRQn
#endif

#ifdef MCU_GDE23
#define GIGADEVICES
#define CPU_FREQUENCY_MHZ 72

#define EEPROM_START_ADD (uint32_t)0x08007C00

#define INTERVAL_TIMER TIMER5
#define TEN_KHZ_TIMER TIMER13
#define UTILITY_TIMER TIMER16
#define COM_TIMER TIMER15
#define APPLICATION_ADDRESS 0x08001000
#define EXTI_LINE EXTI_21
#define TARGET_MIN_BEMF_COUNTS 4
#define USE_ADC
#define COMPARATOR_IRQ ADC_CMP_IRQn
#define COM_TIMER_IRQ TIMER15_IRQn
#ifndef CURRENT_ADC_CHANNEL
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_6
#define CURRENT_ADC_PIN GPIO_PIN_6
#endif
#ifndef VOLTAGE_ADC_CHANNEL
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_3
#define VOLTAGE_ADC_PIN GPIO_PIN_3
#endif
#define DSHOT_PRIORITY_THRESHOLD 50
#endif

#ifdef MCU_AT421
#define ARTERY
#define CPU_FREQUENCY_MHZ 120
#define EEPROM_START_ADD (uint32_t)0x08007C00
#define INTERVAL_TIMER TMR6
#define TEN_KHZ_TIMER TMR14
#define UTILITY_TIMER TMR17
#define COM_TIMER TMR16
#define APPLICATION_ADDRESS 0x08001000
#define EXTI_LINE EXINT_LINE_21
#ifndef TARGET_MIN_BEMF_COUNTS
#define TARGET_MIN_BEMF_COUNTS 3
#endif
#define COMPARATOR_IRQ ADC1_CMP_IRQn
#define USE_ADC
#ifndef CURRENT_ADC_CHANNEL
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_6
#endif
#ifndef CURRENT_ADC_PIN
#define CURRENT_ADC_PIN GPIO_PINS_6
#endif
#ifndef VOLTAGE_ADC_CHANNEL
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_3
#endif
#ifndef VOLTAGE_ADC_PIN
#define VOLTAGE_ADC_PIN GPIO_PINS_3
#endif
#ifndef TEMP_ADC_CHANNEL
#define TEMP_ADC_CHANNEL ADC_CHANNEL_16
#endif
#define DSHOT_PRIORITY_THRESHOLD 50
#define COM_TIMER_IRQ TMR16_GLOBAL_IRQn
#endif

#ifdef MCU_AT415
#define ARTERY
#define CPU_FREQUENCY_MHZ 144
#ifndef EEPROM_START_ADD
#define EEPROM_START_ADD (uint32_t)0x08007C00
#endif
#define INTERVAL_TIMER TMR4
#define TEN_KHZ_TIMER TMR9
#define UTILITY_TIMER TMR10
#define COM_TIMER TMR11
#define APPLICATION_ADDRESS 0x08001000
#define EXTI_LINE EXINT_LINE_19
#define TARGET_MIN_BEMF_COUNTS 3
#define USE_ADC
#define COMPARATOR_IRQ CMP1_IRQn
// #define DSHOT_PRE            95
#define DSHOT_PRIORITY_THRESHOLD 50
#define COM_TIMER_IRQ TMR1_TRG_HALL_TMR11_IRQn
#endif

#ifdef MCU_L431
#define STMICRO
#define CPU_FREQUENCY_MHZ   80
#ifndef EEPROM_START_ADD
#define EEPROM_START_ADD  (uint32_t)0x0800F800
#endif
#define INTERVAL_TIMER     TIM2
#define TEN_KHZ_TIMER      TIM6
#define UTILITY_TIMER      TIM7
#define COM_TIMER          TIM16
#define APPLICATION_ADDRESS 0x08001000
#ifdef USE_COMP_2
#define MAIN_COMP	COMP2
#define EXTI_LINE   LL_EXTI_LINE_22
#endif
#ifdef USE_COMP_1
#define MAIN_COMP	COMP1
#define EXTI_LINE   LL_EXTI_LINE_21
#endif
#ifndef TARGET_MIN_BEMF_COUNTS
#define TARGET_MIN_BEMF_COUNTS 3
#endif
#define COM_TIMER_IRQ TIM1_UP_TIM16_IRQn
#define DSHOT_PRIORITY_THRESHOLD 60
#define COMPARATOR_IRQ COMP_IRQn
#define USE_ADC
#endif

//NXP MCXA153/133
#ifdef MCU_A153
//#define STMICRO
#define NXP
#define CPU_FREQUENCY_MHZ   96		//Is the CPU/System clock, main_clk is 192MHz
#ifndef EEPROM_START_ADD
#define EEPROM_START_ADD  (uint32_t)0xE000		//Flash is 128kB, sector is 8kB, we use 64kB flash
#endif

//Assign correct timer functions to timers
#define INTERVAL_TIMER     CTIMER2
#define TEN_KHZ_TIMER      LPTMR0
#define UTILITY_TIMER      SysTick
#define COM_TIMER          CTIMER1
#define TIM1_AUTORELOAD    8000		//Reloads the PWM at 24kHz. 192MHz clock for FlexPWM

//Define the DMA channels used
#define DMA_CH_DshotPWM			0
#define DMA_CH_DshotPWM_IRQ		DMA_CH0_IRQn
#define DMA_CH_ADC				1
#define DMA_CH_ADC_IRQ			DMA_CH1_IRQn
#define DMA_CH_UART				2
#define DMA_CH_UART_IRQ			DMA_CH2_IRQn

#ifndef TARGET_MIN_BEMF_COUNTS
#define TARGET_MIN_BEMF_COUNTS 3
#endif

//Assign interrupt routines
#define COM_TIMER_IRQ 				CTIMER1_IRQn
#define DSHOT_PRIORITY_THRESHOLD 	60
#define COMP0_IRQ 					CMP0_IRQn
#define COMP1_IRQ 					CMP1_IRQn
#define USE_ADC
#endif

#ifdef MCU_CH32V203
#define WCH
#define NEED_INPUT_READY
#define ERASED_FLASH_BYTE    0x39
#define CPU_FREQUENCY_MHZ    48                     //PWM freq is 48MHz, CPU freq is 96MHz
#define EEPROM_START_ADD     (uint32_t)0x0800f800
#define INTERVAL_TIMER       TIM4
#define TEN_KHZ_TIMER        SysTick
#define UTILITY_TIMER        TIM4
#define COM_TIMER            TIM3                    
#define TIM1_AUTORELOAD      1999
#define APPLICATION_ADDRESS  0x08001000

#define TARGET_MIN_BEMF_COUNTS  3
#define USE_ADC
#define DSHOT_PRIORITY_THRESHOLD 50
#define COM_TIMER_IRQ      TIM3_IRQn

#ifndef USE_PA2_AS_COMP
  #define COMPARATOR_IRQ    EXTI3_IRQn
  #define COMPARATOR_IRQ_2  EXTI4_IRQn
#else
  #define COMPARATOR_IRQ   EXTI2_IRQn
#endif

#endif

#ifndef LOOP_FREQUENCY_HZ
#define LOOP_FREQUENCY_HZ 20000
#endif

#define PID_LOOP_DIVIDER (LOOP_FREQUENCY_HZ / 1000)

// default to no DroneCAN support
#ifndef DRONECAN_SUPPORT
#define DRONECAN_SUPPORT 0
#elif DRONECAN_SUPPORT == 1
// all DroneCAN ESCs use 128k flash layout
#undef EEPROM_START_ADD
#define EEPROM_START_ADD (uint32_t)0x0801F800
#endif

#ifndef NOMINAL_PWM
// use a nominal PWM for commutation via TIM1 of 24kHz
#define NOMINAL_PWM 24000U
#endif

#ifndef TIM1_AUTORELOAD
// calculate commutation timer ARR based on a nominal 24kHz PWM
#define TIM1_AUTORELOAD    ((uint16_t)(CPU_FREQUENCY_MHZ * 1000U * 1000U / NOMINAL_PWM)-1)
#endif

#ifndef POLLING_MODE_THRESHOLD
#define POLLING_MODE_THRESHOLD 2000
#endif
