

#ifndef USE_MAKE

#define AmoxAir_F421
#endif

// used to hold a port/pin in a single 16 bit integer
#define GPIO_PORT_PIN(portnum, pinnum) ((portnum)<<8|(pinnum))

// GLOBAL
// #define USE_ADC_INPUT
// #define USE_ALKAS_DEBUG_LED




#ifdef AmoxAir_F421
#define FIRMWARE_NAME "AT32PB4     "
#define FILE_NAME "AmoxAir_F421"
#define DEAD_TIME 80
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define USE_SERIAL_TELEMETRY
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_3
#define CURRENT_ADC_PIN GPIO_PINS_3
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif



#ifndef FIRMWARE_NAME
/* if you get this then you have forgotten to add the section for your target above */
#error "Missing defines for target"
#endif

/********************************** defaults if not set
 * ***************************/

#ifndef TARGET_VOLTAGE_DIVIDER
#define TARGET_VOLTAGE_DIVIDER 110
#endif

#ifndef SINE_DIVIDER
#define SINE_DIVIDER 2
#endif

#ifndef MILLIVOLT_PER_AMP
#define MILLIVOLT_PER_AMP 20
#endif

#ifndef CURRENT_OFFSET
#define CURRENT_OFFSET 0
#endif

#ifndef TARGET_STALL_PROTECTION_INTERVAL
#define TARGET_STALL_PROTECTION_INTERVAL 6500
#endif

#ifndef RAMP_SPEED_STARTUP
#define RAMP_SPEED_STARTUP 2 // adjusted 2.14 to match duty cycle change between mcu targets.
#endif

#ifndef RAMP_SPEED_LOW_RPM // below commutation interval of 250us
#define RAMP_SPEED_LOW_RPM 6
#endif

#ifndef RAMP_SPEED_HIGH_RPM
#define RAMP_SPEED_HIGH_RPM 16
#endif

/************************************ F051 Hardware Groups
 * ****************************/



#ifdef HARDWARE_GROUP_AT_B

#define MCU_AT421
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN GPIO_PINS_4
#define INPUT_PIN_SOURCE GPIO_PINS_SOURCE4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR3
#define INPUT_DMA_CHANNEL DMA1_CHANNEL4
#define IC_DMA_IRQ_NAME DMA1_Channel5_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PINS_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PINS_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_0
#define PHASE_B_PIN_SOURCE_LOW GPIO_PINS_SOURCE0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PINS_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_7
#define PHASE_C_PIN_SOURCE_LOW GPIO_PINS_SOURCE7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PINS_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_C

#define MCU_AT421
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN GPIO_PINS_2
#define INPUT_PIN_SOURCE GPIO_PINS_SOURCE2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR15
#define INPUT_DMA_CHANNEL DMA1_CHANNEL5
#define IC_DMA_IRQ_NAME DMA1_Channel5_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PINS_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PINS_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_0
#define PHASE_B_PIN_SOURCE_LOW GPIO_PINS_SOURCE0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PINS_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_7
#define PHASE_C_PIN_SOURCE_LOW GPIO_PINS_SOURCE7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PINS_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif



#ifdef HARDWARE_GROUP_AT_E

#define MCU_AT421
#define USE_TIMER_15_CHANNEL_1
// #define USE_PA14_TELEMETRY
#define USE_PA6_TEMP
#define INPUT_PIN GPIO_PINS_2
#define INPUT_PIN_SOURCE GPIO_PINS_SOURCE2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR15
#define INPUT_DMA_CHANNEL DMA1_CHANNEL5
#define IC_DMA_IRQ_NAME DMA1_Channel5_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PINS_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PINS_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_0
#define PHASE_B_PIN_SOURCE_LOW GPIO_PINS_SOURCE0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PINS_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_7
#define PHASE_C_PIN_SOURCE_LOW GPIO_PINS_SOURCE7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PINS_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_F

#define MCU_AT421
#define USE_TIMER_15_CHANNEL_1
// #define USE_PA14_TELEMETRY
// #define USE_PA6_TEMP
#define INPUT_PIN GPIO_PINS_2
#define INPUT_PIN_SOURCE GPIO_PINS_SOURCE2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR15
#define INPUT_DMA_CHANNEL DMA1_CHANNEL5
#define IC_DMA_IRQ_NAME DMA1_Channel5_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PINS_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PINS_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_7
#define PHASE_B_PIN_SOURCE_LOW GPIO_PINS_SOURCE7
#define PHASE_B_GPIO_PORT_LOW GPIOA
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PINS_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_0
#define PHASE_C_PIN_SOURCE_LOW GPIO_PINS_SOURCE0
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PINS_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_045
#define PHASE_A_COMP 0x400000E5 // pa0 Medium Comp Power
#define PHASE_B_COMP 0x400000C5 // pa4
#define PHASE_C_COMP 0x400000D5 // pa5
#endif
#ifdef HARDWARE_GROUP_AT_504
#define PHASE_A_COMP 0x400000D5 // pa5           
#define PHASE_B_COMP 0x400000E5 // pa0
#define PHASE_C_COMP 0x400000C5 // pa4
#endif
#ifdef HARDWARE_GROUP_AT_450
#define PHASE_A_COMP 0x400000C5 // pa4            
#define PHASE_B_COMP 0x400000D5 // pa5
#define PHASE_C_COMP 0x400000E5 // pa0
#endif
#ifdef HARDWARE_GROUP_AT_054
#define PHASE_A_COMP 0x400000E5 // pa0            
#define PHASE_B_COMP 0x400000D5 // pa5
#define PHASE_C_COMP 0x400000C5 // pa4
#endif
#ifdef HARDWARE_GROUP_AT_405
#define PHASE_A_COMP 0x400000C5 // pa4            
#define PHASE_B_COMP 0x400000E5 // pa0
#define PHASE_C_COMP 0x400000D5 // pa5
#endif
#ifdef HARDWARE_GROUP_AT_540
#define PHASE_A_COMP 0x400000D5 // pa5           
#define PHASE_B_COMP 0x400000C5 // pa4
#define PHASE_C_COMP 0x400000E5 // pa0
#endif

#ifdef HARDWARE_GROUP_AT_245
#define PHASE_A_COMP 0x400000F5 // pa2     // works for polling mode
#define PHASE_B_COMP 0x400000C5 // pa4
#define PHASE_C_COMP 0x400000D5 // pa5
#endif

#ifdef     HARDWARE_GROUP_L4_A

#define    MCU_L431
#define    USE_TIMER_15_CHANNEL_1
#define    INPUT_PIN               LL_GPIO_PIN_2
#define    INPUT_PIN_PORT              GPIOA
#define    IC_TIMER_CHANNEL         LL_TIM_CHANNEL_CH1
#define    IC_TIMER_REGISTER          TIM15
#define    IC_TIMER_POINTER           htim15

#define    INPUT_DMA_CHANNEL       LL_DMA_CHANNEL_5
#define    DMA_HANDLE_TYPE_DEF     hdma_tim15_ch1
#define    IC_DMA_IRQ_NAME         DMA1_Channel5_IRQn

#define PHASE_A_GPIO_LOW          LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW         GPIOB
#define PHASE_A_GPIO_HIGH          LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH         GPIOA

#define PHASE_B_GPIO_LOW          LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW         GPIOB
#define PHASE_B_GPIO_HIGH          LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH         GPIOA

#define PHASE_C_GPIO_LOW          LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW         GPIOA
#define PHASE_C_GPIO_HIGH          LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH         GPIOA

#define USE_COMP_1

#ifdef COMP_ORDER_L4_A_045
#define PHASE_A_COMP  LL_COMP_INPUT_MINUS_IO3  // pa0
#define PHASE_B_COMP  LL_COMP_INPUT_MINUS_IO4  // pa4
#define PHASE_C_COMP  LL_COMP_INPUT_MINUS_IO5  // pa5
#endif

#ifdef COMP_ORDER_L4_A_540
#define PHASE_A_COMP  LL_COMP_INPUT_MINUS_IO5  // pa5  /// THIS CONFIG FOR T-MOTOR
#define PHASE_B_COMP  LL_COMP_INPUT_MINUS_IO4  // pa4
#define PHASE_C_COMP  LL_COMP_INPUT_MINUS_IO3  // pa0
#endif

#define COMMON_COMP LL_COMP_INPUT_PLUS_IO3

#define CURRENT_SENSE_ADC_PIN        LL_GPIO_PIN_3
#define VOLTAGE_SENSE_ADC_PIN        LL_GPIO_PIN_6

#define CURRENT_ADC_CHANNEL         LL_ADC_CHANNEL_8
#define VOLTAGE_ADC_CHANNEL         LL_ADC_CHANNEL_11

#endif


#ifdef     HARDWARE_GROUP_L4_B

#define MCU_L431
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA

#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_5
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel5_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA


#define USE_COMP_2
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2  // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO5  // pa5
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO4  // pa4
#define COMMON_COMP  LL_COMP_INPUT_PLUS_IO1
//#define USE_LED_STRIP
//#define WS2812_PIN LL_GPIO_PIN_3

#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_8
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_11
#define ADC_CHANNEL_TEMP LL_ADC_CHANNEL_6

#endif

#ifdef     HARDWARE_GROUP_L4_C

#define    MCU_L431
#define    USE_TIMER_15_CHANNEL_1
#define    INPUT_PIN               LL_GPIO_PIN_2
#define    INPUT_PIN_PORT              GPIOA
#define    IC_TIMER_CHANNEL         LL_TIM_CHANNEL_CH1
#define    IC_TIMER_REGISTER          TIM15
#define    IC_TIMER_POINTER           htim15

#define    INPUT_DMA_CHANNEL       LL_DMA_CHANNEL_5
#define    DMA_HANDLE_TYPE_DEF     hdma_tim15_ch1
#define    IC_DMA_IRQ_NAME         DMA1_Channel5_IRQn

#define PHASE_A_GPIO_LOW          LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW         GPIOB
#define PHASE_A_GPIO_HIGH          LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH         GPIOA

#define PHASE_B_GPIO_LOW          LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW         GPIOB
#define PHASE_B_GPIO_HIGH          LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH         GPIOA

#define PHASE_C_GPIO_LOW          LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW         GPIOA
#define PHASE_C_GPIO_HIGH          LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH         GPIOA

#define USE_COMP_1

#define COMMON_COMP LL_COMP_INPUT_PLUS_IO3  //pa1

#define CURRENT_SENSE_ADC_PIN        LL_GPIO_PIN_3
#define VOLTAGE_SENSE_ADC_PIN        LL_GPIO_PIN_6

#define CURRENT_ADC_CHANNEL         LL_ADC_CHANNEL_8
#define VOLTAGE_ADC_CHANNEL         LL_ADC_CHANNEL_11

#endif

#ifdef HARDWARE_GROUP_L4_045
#define PHASE_A_COMP  LL_COMP_INPUT_MINUS_IO3  // pa0
#define PHASE_B_COMP  LL_COMP_INPUT_MINUS_IO4  // pa4
#define PHASE_C_COMP  LL_COMP_INPUT_MINUS_IO5  // pa5
#endif

#ifdef HARDWARE_GROUP_L4_054
#define PHASE_A_COMP  LL_COMP_INPUT_MINUS_IO3  // pa0
#define PHASE_B_COMP  LL_COMP_INPUT_MINUS_IO5  // pa5
#define PHASE_C_COMP  LL_COMP_INPUT_MINUS_IO4  // pa4
#endif

#ifdef     HARDWARE_GROUP_L4_N

#define    MCU_L431
#define    USE_TIMER_15_CHANNEL_1
#define    INPUT_PIN               LL_GPIO_PIN_2
#define    INPUT_PIN_PORT              GPIOA
#define    IC_TIMER_CHANNEL         LL_TIM_CHANNEL_CH1
#define    IC_TIMER_REGISTER          TIM15
#define    IC_TIMER_POINTER           htim15

#define    INPUT_DMA_CHANNEL       LL_DMA_CHANNEL_5
#define    DMA_HANDLE_TYPE_DEF     hdma_tim15_ch1
#define    IC_DMA_IRQ_NAME         DMA1_Channel5_IRQn

#define PHASE_A_GPIO_LOW          LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW         GPIOB
#define PHASE_A_GPIO_HIGH          LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH         GPIOA

#define PHASE_B_GPIO_LOW          LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW         GPIOB
#define PHASE_B_GPIO_HIGH          LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH         GPIOA

#define PHASE_C_GPIO_LOW          LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW         GPIOA
#define PHASE_C_GPIO_HIGH          LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH         GPIOA

#define USE_COMP_2
#define PHASE_A_COMP  LL_COMP_INPUT_MINUS_IO2  // pb7
#define PHASE_B_COMP  LL_COMP_INPUT_MINUS_IO5  // pa5
#define PHASE_C_COMP  LL_COMP_INPUT_MINUS_IO4  // pa4
#define COMMON_COMP   LL_COMP_INPUT_PLUS_IO1


#define CURRENT_SENSE_ADC_PIN        LL_GPIO_PIN_3
#define VOLTAGE_SENSE_ADC_PIN        LL_GPIO_PIN_6

#define CURRENT_ADC_CHANNEL         LL_ADC_CHANNEL_8
#define VOLTAGE_ADC_CHANNEL         LL_ADC_CHANNEL_11

#endif

//NXP hardware group of the MCXA153
#ifdef     HARDWARE_GROUP_NXP_MCXA153

#define    MCU_A153

//This is the Dshot/PWM input pin
#define    INPUT_PIN            	2		//P1.2
#define    INPUT_PIN_PORT        	PORT1
#define    INPUT_PIN_GPIO			GPIO1
#define    INPUT_PIN_CAPTURE_INP	1		//CT_INP0, check datasheet for correct value
#define    INPUT_PIN_ALT_FUNC		5		//CTIMER Capture input

//This is the Dshot/PWM timer
#define    IC_TIMER_REGISTER    	CTIMER0

//This is the DMA used for the Dshot/PWM data transfer
#define    INPUT_DMA_CHANNEL       	0 				//DMA channel 0
#define    IC_DMA_IRQ_NAME         	DMA_CH0_IRQn

//Assign the pins/PORTs/GPIOs for each gate signal
#define PHASE_A_PIN_LOW       		0		//Pin number
#define PHASE_A_PORT_LOW   			PORT3	//PORT number
#define PHASE_A_GPIO_LOW   			GPIO3	//GPIO number
#define PHASE_A_PIN_HIGH       		1
#define PHASE_A_PORT_HIGH    		PORT3
#define PHASE_A_GPIO_HIGH			GPIO3

#define PHASE_B_PIN_LOW         	8
#define PHASE_B_PORT_LOW     		PORT3
#define PHASE_B_GPIO_LOW			GPIO3
#define PHASE_B_PIN_HIGH      		9
#define PHASE_B_PORT_HIGH   		PORT3
#define PHASE_B_GPIO_HIGH			GPIO3

#define PHASE_C_PIN_LOW       		10
#define PHASE_C_PORT_LOW   			PORT3
#define PHASE_C_GPIO_LOW			GPIO3
#define PHASE_C_PIN_HIGH   			11
#define PHASE_C_PORT_HIGH			PORT3
#define PHASE_C_GPIO_HIGH			GPIO3

#define PHASE_A_COMP_INP  	3  		//P1.0 COMP0_IN3
#define PHASE_A_COMP_UNIT 	CMP0
#define PHASE_B_COMP_INP  	3  		//P1.1 COMP1_IN3
#define PHASE_B_COMP_UNIT 	CMP1
#define PHASE_C_COMP_INP  	1  		//P1.3 COMP0_IN1
#define PHASE_C_COMP_UNIT 	CMP0

#define COMMON_COMP0_INP	0		//P2.2 COMP0_IN0
#define COMMON_COMP1_INP	0		//P2.3 COMP1_IN0

//Assign UART pins and module
#define SERIAL_TELEMETRY				LPUART1
#define SERIAL_TELEMETRY_MODULE 		1
#define SERIAL_TELEMETRY_TX_PORT 		PORT1	//P1.9
#define SERIAL_TELEMETRY_TX_PIN 		9
#define SERIAL_TELEMETRY_TX_ALT_FUNC 	2

//Assign ADC pins and channels
#define CURRENT_SENSE_ADC_PIN     	7		//P2.7
#define VOLTAGE_SENSE_ADC_PIN      	16		//P2.16
#define SENSE_ADC_PORT 				PORT2

#define CURRENT_ADC_CHANNEL         7
#define VOLTAGE_ADC_CHANNEL         6
#define TEMP_ADC_CHANNEL 			26

//#define LOOP_FREQUENCY_HZ 10000
#endif
/************************************ G031 Hardware Groups
 * ************************************************/

#ifdef HARDWARE_GROUP_G031_A

#define MCU_G031
//#define EXTI_TYPE_BAC            // ??

#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_6
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_EXTI_PORT GPIOC
#define PHASE_B_EXTI_PORT GPIOB
#define PHASE_C_EXTI_PORT GPIOB

#define PHASE_A_EXTI_PIN LL_GPIO_PIN_14
#define PHASE_B_EXTI_PIN LL_GPIO_PIN_7
#define PHASE_C_EXTI_PIN LL_GPIO_PIN_1

#define PHASE_A_EXTI_LINE 14
#define PHASE_B_EXTI_LINE 7
#define PHASE_C_EXTI_LINE 1

#define SYSCFG_EXTI_PORTA LL_EXTI_CONFIG_PORTC
#define SYSCFG_EXTI_PORTB LL_EXTI_CONFIG_PORTB
#define SYSCFG_EXTI_PORTC LL_EXTI_CONFIG_PORTB

#define SYSCFG_EXTI_LINEA LL_EXTI_CONFIG_LINE14
#define SYSCFG_EXTI_LINEB LL_EXTI_CONFIG_LINE7
#define SYSCFG_EXTI_LINEC LL_EXTI_CONFIG_LINE1

#define PHASE_A_LL_EXTI_LINE LL_EXTI_LINE_14
#define PHASE_B_LL_EXTI_LINE LL_EXTI_LINE_7
#define PHASE_C_LL_EXTI_LINE LL_EXTI_LINE_1

#define EXTI_IRQ1_NAME EXTI0_1_IRQn
#define EXTI_IRQ2_NAME EXTI4_15_IRQn


//#define PHASE_A_GPIO_LOW LL_GPIO_PIN_15
//#define PHASE_A_GPIO_PORT_LOW GPIOB
//#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
//#define PHASE_A_GPIO_PORT_HIGH GPIOA

//#define PHASE_B_GPIO_LOW LL_GPIO_PIN_14
//#define PHASE_B_GPIO_PORT_LOW GPIOB
//#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
//#define PHASE_B_GPIO_PORT_HIGH GPIOA

//#define PHASE_C_GPIO_LOW LL_GPIO_PIN_13
//#define PHASE_C_GPIO_PORT_LOW GPIOB
//#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
//#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_14
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_13
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_C_GPIO_PORT_HIGH GPIOA



#define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5

#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif




/************************************ MCU COMMON PERIPHERALS
 * **********************************************/

#ifdef MCU_AT421
#define ARTERY
#define CPU_FREQUENCY_MHZ 120
#define EEPROM_START_ADD (uint32_t)0x08007C00
#define INTERVAL_TIMER TMR6
#define TEN_KHZ_TIMER TMR14
#define UTILITY_TIMER TMR17
#define COM_TIMER TMR16
#define APPLICATION_ADDRESS 0x08001000
#define EXTI_LINE EXINT_LINE_21
#ifndef TARGET_MIN_BEMF_COUNTS
#define TARGET_MIN_BEMF_COUNTS 3
#endif
#define COMPARATOR_IRQ ADC1_CMP_IRQn
#define USE_ADC
#ifndef CURRENT_ADC_CHANNEL
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_6
#endif
#ifndef CURRENT_ADC_PIN
#define CURRENT_ADC_PIN GPIO_PINS_6
#endif
#ifndef VOLTAGE_ADC_CHANNEL
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_3
#endif
#ifndef VOLTAGE_ADC_PIN
#define VOLTAGE_ADC_PIN GPIO_PINS_3
#endif
#ifndef TEMP_ADC_CHANNEL
#define TEMP_ADC_CHANNEL ADC_CHANNEL_16
#endif
#define DSHOT_PRIORITY_THRESHOLD 50
#define COM_TIMER_IRQ TMR16_GLOBAL_IRQn
#endif




#endif

#ifndef LOOP_FREQUENCY_HZ
#define LOOP_FREQUENCY_HZ 20000
#endif

#define PID_LOOP_DIVIDER (LOOP_FREQUENCY_HZ / 1000)

// default to no DroneCAN support
#ifndef DRONECAN_SUPPORT
#define DRONECAN_SUPPORT 0
#elif DRONECAN_SUPPORT == 1
// all DroneCAN ESCs use 128k flash layout
#undef EEPROM_START_ADD
#define EEPROM_START_ADD (uint32_t)0x0801F800
#endif

#ifndef NOMINAL_PWM
// use a nominal PWM for commutation via TIM1 of 24kHz
#define NOMINAL_PWM 24000U
#endif

#ifndef TIM1_AUTORELOAD
// calculate commutation timer ARR based on a nominal 24kHz PWM
#define TIM1_AUTORELOAD    ((uint16_t)(CPU_FREQUENCY_MHZ * 1000U * 1000U / NOMINAL_PWM)-1)
#endif

#ifndef POLLING_MODE_THRESHOLD
#define POLLING_MODE_THRESHOLD 2000
#endif
